name: Approve shell script pull request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Approve shell script pull request
      run: |
        git config --global user.email "timabuntu@gmail.com"
        git config --global user.name "thiago lopes de mello"
        git remote set-url origin https://x-access-token:${{ secrets.PULL_TOKEN }}@github.com/${{ github.repository }}.git
        git fetch
        git checkout ${{ github.head_ref }}
        for file in $(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep ".sh$")
        do
          bash -n $file
        done
        git commit -a -m "Approving shell script pull request"
        git push origin ${{ github.head_ref }}:${{ github.base_ref }}
